### ISSUE TITLE
functions.php

### ISSUE THREAD

**Issue by RaymondSchnyder** [ydkmlt84/embyvites#1]
the file functions.php is required to work with this, but the file is not there

**Comment by ydkmlt84** [comment]
This was something I made for myself and the functions.php file that I used is part of Organizr.
  All this does is send the prospective user to create an Emby Connect account. Then step 2 gives them the ability to email me with their username, and some more information, so that I can manually create an account for them on my personal Emby server, and link it to their Emby connect. 
  Is that something that you’re trying to do?

**Comment by RaymondSchnyder** [comment]
I thought your github project is a wrapper around the emby api to automatically create emby users :/
sorry about that

**Comment by ydkmlt84** [comment]
I wish! I couldn’t ever figure out a way to do it. I still look into it every now and then.

**Comment by RaymondSchnyder** [comment]
It should be possible by building a wrapper around the Javascript APIclient.
Like you could build basic functions like account creation, account deletion, password reseting...
I will look into it, maybe its easier now

**Comment by RaymondSchnyder** [comment]
Yesterday i made great progress on this, im able now to get userinfo and all users through a javascript based page, im not ready yet to modify information, as the emby api endpoint is pure horror. i will show you my progress when im home
